all:
	gcc -Wall -Wextra -Werror asfds.c wrappers.c -o asfds
	gcc -Wall -Wextra -Werror fdscat.c wrappers.c -o fdscat

debug:
	gcc -Wall -Wextra asfds.c wrappers.c -o asfds
	gcc -Wall -Wextra fdscat.c wrappers.c -o fdscat
